version: '3.8'

services:
  database:
    image: mysql:latest
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    environment:
      env_file: ./.env
    ports:
      - "3306:3306"
    restart: always

  phpserver:
    build: ./docker
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    restart: always
