version: '3.8'

services:
  database:
    image: mysql:8.0
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      EMPTYMYSQL_USER: ${MYSQL_USER}
      ALLOWMYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3308:3306"
    restart: always

  reservations:
     build:
        context: ./packages/reservations
        dockerfile: prod.Dockerfile
     healthcheck:
       test: ["CMD-SHELL", "curl -f http://localhost:9000/ || exit 1"]
       interval: 1m
       timeout: 10s
       retries: 3
     ports:
       - "3234:9000"
     restart: always
     env_file:
       - ./packages/reservations/.env
     depends_on:
       - database
     networks:
       - symfony-microservices
     logging:
       driver: json-file
       options:
         max-size: "10m"
         max-file: "3"

  auth:
    build:
      context: ./packages/auth
      dockerfile: prod.Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/ || exit 1" ]
      interval: 1m
      timeout: 10s
      retries: 3
    ports:
      - "3235:9000"
    restart: always
    env_file:
      - ./packages/auth/.env
    depends_on:
      - database
    networks:
      - symfony-microservices
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --interval 86400   # 24 hours in seconds
      - --cleanup          # Remove old images after update
      - --label-enable     # Watch only labeled containers
      - --label=com.centurylinklabs.watchtower.enable=true  # Label to watch
    environment:
      - WATCHTOWER_NOTIFICATIONS=christiandominguez
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=your-email@example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=your-email@example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=your-email@example.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=your-email-password

networks:
  symfony-microservices:
    driver: bridge



## reservations: port 3234, auth:  3235, payments: 3236, and notifications: 3237.